version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "3000:3000" # Porta que seu backend usa
    environment:
      - NODE_ENV=production

  frontend:
    build: ./front
    ports:
      - "80:80" # Porta para acessar no navegador
    depends_on:
      - backend